POST https://testshop.dfx.swiss/wc-api/dfx_gateway/ HTTP/1.1
Content-Type: application/json
X-Payload-Signature: vVGM8VgZAKKeJMfiaVrK1APfz/7rq5MN3Rc97UIqav4ni73/IcHCBhTkaRQsbw7l8dbt2D75q5k1VjN7MiKzTfgl8oSwCVk+19OB6MT2HtOchq9dsxhP8AnZaZnoLghWQ4xd7jKDjTaesH6zehproaU0PRdpavP/9ytDuikhQFrnoAjzu8zedt+7v+h/IB3bZHbkKgyZmVyCX4reLLxiSAX9zJzED86Lmrq1d/YODzlaS4k8Lg62fuimIWZWK8j32lWx0OxZOaNyqP0eAoCDRTOgW9MZoEBRXjrOhyOO/Jw7vmc7h0rEpOJsZpOKkmRBCKkVrjQc0WhOaqVFmB3kDw==

{"id":690,"routeId":16760,"externalId":"324/0.02","webhookUrl":"https://testshop.dfx.swiss/wc-api/dfx_gateway/","recipient":{"name":"","address":{"street":null,"houseNumber":null,"city":null,"zip":null},"phone":null,"mail":null,"website":null},"status":"Active","url":"https://api.dfx.swiss/v1/lnurlp/pl_9710eb","lnurl":"LNURL1DP68GURN8GHJ7CTSDYHXGENC9EEHW6TNWVHHVVF0D3H82UNVWQHHQMZL8YMNZVR9VGXQC2AK","payment":{"id":1331,"externalId":"324/0.02","status":"Completed","amount":0.02,"currency":"CHF","mode":"Single","expiryDate":"2024-12-09T13:53:39.000Z","txCount":1,"isConfirmed":false,"url":"https://api.dfx.swiss/v1/lnurlp/plp_581938","lnurl":"LNURL1DP68GURN8GHJ7CTSDYHXGENC9EEHW6TNWVHHVVF0D3H82UNVWQHHQMRSTU6NSVFEXVUQTLETW8"}}